version: "3.9"
services:
  nginx:
    image: nginx
    container_name: sanhak-nginx-server
    restart: always
    ports:
      - "8887:10080"
    networks:
      - sanhak-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  fast-api:
    image: rhlehfndvkd7557/sanhak-fast-api:1
    container_name: sanhak-fast-api-server
    restart: always
    ports:
      - "8777:8777"
    networks:
      - sanhak-net

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: sanhak-mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: hyundaitransys
      MYSQL_USER: sanhak
      MYSQL_PASSWORD: sanhak
      MYSQL_ROOT_PASSWORD: rhleh2160
    ports:
      - "3333:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - sanhak-net
networks:
  sanhak-net: